#include "def.h"

int colorhl1=60,colorhl2=10,colorhl3=165,colorhl4=310,colorhl5=70,colorhl6=140;				//low trigger h color	
int	colorhh1=140,colorhh2=40,colorhh3=195,colorhh4=370,colorhh5=95,colorhh6=225;			//high trigger h color
float 	colorsl1=0.25,colorsl2=0.49,colorsl3=0.65,colorsl4=0.35,colorsl5=0.70,colorsl6=0.20;		//low trigger s color				
float	colorsh1=2,colorsh2=2,colorsh3=2,colorsh4=2,colorsh5=2,colorsh6=2;				//high trigger s color
int	colorvl1=50,colorvl2=140,colorvl3=165,colorvl4=120,colorvl5=70,colorvl6=50;			//low trigger v color 
int	colorvh1=180,colorvh2=260,colorvh3=195,colorvh4=260,colorvh5=95,colorvh6=180;		//high trigger v color

int ipvalue;

void initwithfiles(void){
if(wifi==1){				//If wifi flag active cet raspberry identfier from ip.conf file 
		FILE * pFile3;
		pFile3=fopen("ip.conf","rb");
		if(pFile3==NULL)perror("Error opening file");
		ipvalue=0;
		ipvalue=ipvalue+((fgetc(pFile3)-48)*100);
		ipvalue=ipvalue+((fgetc(pFile3)-48)*10);
		ipvalue=ipvalue+((fgetc(pFile3)-48));
		message[0]=ipvalue;
		fclose(pFile3);
	}


	//get trigger values from color.conf file
	int value=0;
	FILE * pFile4;
	pFile4=fopen("color.conf","rb");
	if(pFile4==NULL)perror("Error opening file");
	colorhl1=0;
	value=fgetc(pFile4);
	colorhl1=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorhl1*=10;
		colorhl1+=value-48;
		value=fgetc(pFile4);			
	}
	value=fgetc(pFile4);
	colorhl2=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorhl2*=10;
		colorhl2+=value-48;
		value=fgetc(pFile4);		
	}
	value=fgetc(pFile4);
	colorhl3=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorhl3*=10;
		colorhl3+=value-48;
		value=fgetc(pFile4);		
	}
	value=fgetc(pFile4);
	colorhl4=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorhl4*=10;
		colorhl4+=value-48;
		value=fgetc(pFile4);		
	}
	value=fgetc(pFile4);
	colorhl5=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorhl5*=10;
		colorhl5+=value-48;
		value=fgetc(pFile4);		
	}
	value=fgetc(pFile4);
	colorhl6=value-48;
	value=fgetc(pFile4);
	while(value!=10)
	{
		colorhl6*=10;
		colorhl6+=value-48;
		value=fgetc(pFile4);		
	}
	value=fgetc(pFile4);
	colorhh1=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorhh1*=10;
		colorhh1+=value-48;
		value=fgetc(pFile4);			
	}
	value=fgetc(pFile4);
	colorhh2=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorhh2*=10;
		colorhh2+=value-48;
		value=fgetc(pFile4);		
	}
	value=fgetc(pFile4);
	colorhh3=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorhh3*=10;
		colorhh3+=value-48;
		value=fgetc(pFile4);		
	}
	value=fgetc(pFile4);
	colorhh4=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorhh4*=10;
		colorhh4+=value-48;
		value=fgetc(pFile4);		
	}
	value=fgetc(pFile4);
	colorhh5=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorhh5*=10;
		colorhh5+=value-48;
		value=fgetc(pFile4);		
	}
	value=fgetc(pFile4);
	colorhh6=value-48;
	value=fgetc(pFile4);
	while(value!=10)
	{
		colorhh6*=10;
		colorhh6+=value-48;
		value=fgetc(pFile4);		
	}
	
	
	
	value=fgetc(pFile4);
	colorsl1=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorsl1*=10;
		colorsl1+=value-48;
		value=fgetc(pFile4);			
	}
	colorsl1/=100;
	value=fgetc(pFile4);
	colorsl2=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorsl2*=10;
		colorsl2+=value-48;
		value=fgetc(pFile4);		
	}
	colorsl2/=100;
	value=fgetc(pFile4);
	colorsl3=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorsl3*=10;
		colorsl3+=value-48;
		value=fgetc(pFile4);		
	}
	colorsl3/=100;
	value=fgetc(pFile4);
	colorsl4=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorsl4*=10;
		colorsl4+=value-48;
		value=fgetc(pFile4);		
	}
	colorsl4/=100;
	value=fgetc(pFile4);
	colorsl5=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorsl5*=10;
		colorsl5+=value-48;
		value=fgetc(pFile4);		
	}
	colorsl5/=100;
	value=fgetc(pFile4);
	colorsl6=value-48;
	value=fgetc(pFile4);
	while(value!=10)
	{
		colorsl6*=10;
		colorsl6+=value-48;
		value=fgetc(pFile4);		
	}
	colorsl6/=100;
	value=fgetc(pFile4);
	colorsh1=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorsh1*=10;
		colorsh1+=value-48;
		value=fgetc(pFile4);			
	}
	colorsh1/=100;
	value=fgetc(pFile4);
	colorsh2=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorsh2*=10;
		colorsh2+=value-48;
		value=fgetc(pFile4);		
	}
	colorsh2/=100;
	value=fgetc(pFile4);
	colorsh3=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorsh3*=10;
		colorsh3+=value-48;
		value=fgetc(pFile4);		
	}
	colorsh3/=100;
	value=fgetc(pFile4);
	colorsh4=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorsh4*=10;
		colorsh4+=value-48;
		value=fgetc(pFile4);		
	}
	colorsh4/=100;
	value=fgetc(pFile4);
	colorsh5=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorsh5*=10;
		colorsh5+=value-48;
		value=fgetc(pFile4);		
	}
	colorsh5/=100;
	value=fgetc(pFile4);
	colorsh6=value-48;
	value=fgetc(pFile4);
	while(value!=10)
	{
		colorsh6*=10;
		colorsh6+=value-48;
		value=fgetc(pFile4);		
	}
	colorsh6/=100;
	
	
	value=fgetc(pFile4);
	colorvl1=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorvl1*=10;
		colorvl1+=value-48;
		value=fgetc(pFile4);			
	}
	value=fgetc(pFile4);
	colorvl2=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorvl2*=10;
		colorvl2+=value-48;
		value=fgetc(pFile4);		
	}
	value=fgetc(pFile4);
	colorvl3=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorvl3*=10;
		colorvl3+=value-48;
		value=fgetc(pFile4);		
	}
	value=fgetc(pFile4);
	colorvl4=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorvl4*=10;
		colorvl4+=value-48;
		value=fgetc(pFile4);		
	}
	value=fgetc(pFile4);
	colorvl5=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorvl5*=10;
		colorvl5+=value-48;
		value=fgetc(pFile4);		
	}
	value=fgetc(pFile4);
	colorvl6=value-48;
	value=fgetc(pFile4);
	while(value!=10)
	{
		colorvl6*=10;
		colorvl6+=value-48;
		value=fgetc(pFile4);		
	}
	value=fgetc(pFile4);
	colorvh1=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorvh1*=10;
		colorvh1+=value-48;
		value=fgetc(pFile4);			
	}
	value=fgetc(pFile4);
	colorvh2=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorvh2*=10;
		colorvh2+=value-48;
		value=fgetc(pFile4);		
	}
	value=fgetc(pFile4);
	colorvh3=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorvh3*=10;
		colorvh3+=value-48;
		value=fgetc(pFile4);		
	}
	value=fgetc(pFile4);
	colorvh4=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorvh4*=10;
		colorvh4+=value-48;
		value=fgetc(pFile4);		
	}
	value=fgetc(pFile4);
	colorvh5=value-48;
	value=fgetc(pFile4);
	while(value!=9)
	{
		colorvh5*=10;
		colorvh5+=value-48;
		value=fgetc(pFile4);		
	}
	value=fgetc(pFile4);
	colorvh6=value-48;
	value=fgetc(pFile4);
	while(value!=10)
	{
		colorvh6*=10;
		colorvh6+=value-48;
		value=fgetc(pFile4);		
	}
	fclose(pFile4);
	
	value=0;
	FILE * pFile5;
	pFile5=fopen("awb.conf","rb");
	if(pFile5==NULL)perror("Error opening file");
	
	int awbr=0,awbb=0;
	value=fgetc(pFile5);
	awbr=value-48;
	value=fgetc(pFile5);
	while(value!=9)
	{
		awbr*=10;
		awbr+=value-48;
		value=fgetc(pFile5);			
	}
	value=fgetc(pFile5);
	awbb=value-48;
	value=fgetc(pFile5);
	while(value!=9)
	{
		awbb*=10;
		awbb+=value-48;
		value=fgetc(pFile5);			
	}
					
	bluebalance.set.value=awbb;
	redbalance.set.value=awbr;
	
	fclose(pFile5);
	
		printf("\033[4;1H\033[J");
	printf("ip: %d\t awb blue: %d\t awb red: %d\n",ipvalue,awbb,awbr);
	printf("%d\t%d\t%d\t%d\t%d\t%d\n",colorhl1,colorhl2,colorhl3,colorhl4,colorhl5,colorhl6);
	printf("%d\t%d\t%d\t%d\t%d\t%d\n",colorhh1,colorhh2,colorhh3,colorhh4,colorhh5,colorhh6);
	printf("%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\n",colorsl1,colorsl2,colorsl3,colorsl4,colorsl5,colorsl6);
	printf("%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\n",colorsh1,colorsh2,colorsh3,colorsh4,colorsh5,colorsh6);
	printf("%d\t%d\t%d\t%d\t%d\t%d\n",colorvl1,colorvl2,colorvl3,colorvl4,colorvl5,colorvl6);
	printf("%d\t%d\t%d\t%d\t%d\t%d\n",colorvh1,colorvh2,colorvh3,colorvh4,colorvh5,colorvh6);
}
